[package]
name = "aoc-2019"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
num-derive = "0.3.3"
num-traits = "0.2.15"
